#  http://localhost:8084/服务的名字/url
#  http://localhost:8084/consumer-demo/c/ping
logging:
  level:
    com.netflix: DEBUG
server:
  port: 8084
spring:
  application:
    name: micreoservice-gateway-zuul-demo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

zuul:
  routes:
    consumer-demo: /c/**
    #忽略转发的服务 ，分割
  #ignored-services: consumer-demo