management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #指定Eureka服务端地址
spring:
  application:
    name: provicer-demo