server:
  port: 8081
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #指定Eureka服务端地址
spring:
  application:
    name: consumer-demo
# 设置feign日志
logging:
  level:
    com.example.consumer_demo.feignClient.ConsumerConfiguration: debug
feign:
  hystrix:
    enabled: true
  client:
    config:
      PROVICER-DEMO:
        loggerLevel: full
management:
  endpoints:
    health:
      # 是否展示健康检查详情
      show-details: always
    web:
      exposure:
        include: 'hystrix.stream'
turbine:
  aggregator:
    cluster-config: consumer-demo,provicer-demo
    clusterNameExpression: "'default'"

#集群
# Feign 默认集成ribbon 负载均衡使用随机规
PROVICER-DEMO:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule